# Generated by Django 4.2.30 on 2026-05-13 00:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "key",
                    models.CharField(max_length=100, unique=True, verbose_name="Chave"),
                ),
                (
                    "value",
                    models.TextField(blank=True, null=True, verbose_name="Valor"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Configuração",
                "verbose_name_plural": "Configurações",
            },
        ),
        migrations.CreateModel(
            name="WhatsAppTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("reminder", "Lembrete"),
                            ("collection", "Cobrança"),
                            ("weekly", "Cobrança semanal"),
                            ("welcome", "Boas-vindas"),
                            ("thanks", "Agradecimento"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("template", models.TextField(verbose_name="Template")),
                ("active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
            ],
            options={
                "verbose_name": "Template WhatsApp",
                "verbose_name_plural": "Templates WhatsApp",
            },
        ),
        migrations.CreateModel(
            name="WhatsAppMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("reminder", "Lembrete"),
                            ("collection", "Cobrança"),
                            ("weekly", "Cobrança semanal"),
                            ("welcome", "Boas-vindas"),
                            ("thanks", "Agradecimento"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("message", models.TextField(verbose_name="Mensagem")),
                ("sent", models.BooleanField(default=False, verbose_name="Enviado")),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Enviado em"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whatsapp_messages",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensagem WhatsApp",
                "verbose_name_plural": "Mensagens WhatsApp",
                "ordering": ["-created_at"],
            },
        ),
    ]
