# Generated by Django 4.2.30 on 2026-05-13 02:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AISettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Chat IA", max_length=100, verbose_name="Nome"
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        choices=[
                            ("gpt-4o-mini", "GPT-4o Mini"),
                            ("gpt-4o", "GPT-4o"),
                            ("gpt-4-turbo", "GPT-4 Turbo"),
                            ("claude-3-haiku", "Claude 3 Haiku"),
                            ("claude-3-sonnet", "Claude 3 Sonnet"),
                        ],
                        default="gpt-4o-mini",
                        max_length=50,
                        verbose_name="Modelo",
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="API Key"
                    ),
                ),
                (
                    "api_url",
                    models.URLField(
                        default="https://api.openai.com/v1/chat/completions",
                        verbose_name="URL da API",
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(default="", verbose_name="Prompt do Sistema"),
                ),
                ("active", models.BooleanField(default=False, verbose_name="Ativo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Configuração de IA",
                "verbose_name_plural": "Configurações de IA",
            },
        ),
        migrations.CreateModel(
            name="ChatConversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Ativa"), ("closed", "Encerrada")],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chats",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversa",
                "verbose_name_plural": "Conversas",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "Cliente"),
                            ("assistant", "Assistente"),
                            ("system", "Sistema"),
                        ],
                        max_length=20,
                        verbose_name="Papel",
                    ),
                ),
                ("content", models.TextField(verbose_name="Conteúdo")),
                (
                    "audio_url",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="URL do Áudio"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Metadados"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.chatconversation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensagem",
                "verbose_name_plural": "Mensagens",
                "ordering": ["created_at"],
            },
        ),
    ]
