# Generated by Django 4.2.30 on 2026-05-14 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aisettings",
            name="provider",
            field=models.CharField(
                choices=[("openai", "OpenAI"), ("openrouter", "OpenRouter")],
                default="openai",
                max_length=20,
                verbose_name="Provedor",
            ),
        ),
        migrations.AlterField(
            model_name="aisettings",
            name="model",
            field=models.CharField(
                choices=[
                    ("gpt-4o-mini", "GPT-4o Mini"),
                    ("gpt-4o", "GPT-4o"),
                    ("gpt-4-turbo", "GPT-4 Turbo"),
                    ("claude-3-haiku", "Claude 3 Haiku"),
                    ("claude-3-sonnet", "Claude 3 Sonnet"),
                    ("qwen/qwen-vl-plus", "Qwen VL Plus (OpenRouter)"),
                ],
                default="gpt-4o-mini",
                max_length=50,
                verbose_name="Modelo",
            ),
        ),
    ]
