# Generated by Django 4.2.30 on 2026-05-14 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_aisettings_provider_alter_aisettings_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aisettings",
            name="model",
            field=models.CharField(
                choices=[
                    ("gpt-4o-mini", "GPT-4o Mini"),
                    ("gpt-4o", "GPT-4o"),
                    ("gpt-4-turbo", "GPT-4 Turbo"),
                    ("claude-3-haiku", "Claude 3 Haiku"),
                    ("claude-3-sonnet", "Claude 3 Sonnet"),
                    ("qwen/qwen2-vl-72b-instruct", "Qwen2 VL 72B"),
                    (
                        "meta-llama/llama-3.2-90b-vision-instruct",
                        "Llama 3.2 90B Vision",
                    ),
                    (
                        "meta-llama/llama-3.2-11b-vision-instruct",
                        "Llama 3.2 11B Vision",
                    ),
                    ("anthropic/claude-3.5-sonnet", "Claude 3.5 Sonnet"),
                ],
                default="gpt-4o-mini",
                max_length=50,
                verbose_name="Modelo",
            ),
        ),
    ]
