# Generated by Django 4.2.30 on 2026-05-14 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_alter_aisettings_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aisettings",
            name="model",
            field=models.CharField(
                choices=[
                    ("gpt-4o-mini", "GPT-4o Mini"),
                    ("gpt-4o", "GPT-4o"),
                    ("gpt-4-turbo", "GPT-4 Turbo"),
                    ("gpt-4", "GPT-4"),
                    ("claude-3-haiku", "Claude 3 Haiku"),
                    ("claude-3-sonnet", "Claude 3 Sonnet"),
                    ("claude-3-opus", "Claude 3 Opus"),
                    ("llama-3.2-90b-vision-preview", "Llama 3.2 90B Vision (Groq)"),
                    ("llama-3.2-11b-vision-preview", "Llama 3.2 11B Vision (Groq)"),
                    ("llama-3.1-70b-versatile", "Llama 3.1 70B (Groq)"),
                ],
                default="gpt-4o-mini",
                max_length=50,
                verbose_name="Modelo",
            ),
        ),
        migrations.AlterField(
            model_name="aisettings",
            name="provider",
            field=models.CharField(
                choices=[
                    ("openai", "OpenAI"),
                    ("openrouter", "OpenRouter"),
                    ("groq", "Groq (Gratuito)"),
                ],
                default="openai",
                max_length=20,
                verbose_name="Provedor",
            ),
        ),
    ]
