# Generated by Django 4.2.30 on 2026-05-14 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_alter_aisettings_model_alter_aisettings_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aisettings",
            name="model",
            field=models.CharField(
                choices=[
                    ("gpt-4o-mini", "GPT-4o Mini"),
                    ("gpt-4o", "GPT-4o"),
                    ("gpt-4-turbo", "GPT-4 Turbo"),
                    ("gpt-4", "GPT-4"),
                    ("claude-3-haiku", "Claude 3 Haiku"),
                    ("claude-3-sonnet", "Claude 3 Sonnet"),
                    ("claude-3-opus", "Claude 3 Opus"),
                    ("llama-3.3-70b-versatile", "Llama 3.3 70B"),
                    ("mixtral-8x7b-32768", "Mixtral 8x7B"),
                    ("gemini-1.5-flash-8k", "Gemini 1.5 Flash 8K"),
                ],
                default="gpt-4o-mini",
                max_length=50,
                verbose_name="Modelo",
            ),
        ),
        migrations.AlterField(
            model_name="aisettings",
            name="provider",
            field=models.CharField(
                choices=[("openai", "OpenAI")],
                default="openai",
                max_length=20,
                verbose_name="Provedor",
            ),
        ),
    ]
