# Generated by Django 4.2.30 on 2026-05-13 00:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("products", models.JSONField(default=list, verbose_name="Produtos")),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Total"
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Valor pago",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("paid", "Pago"),
                            ("partial", "Parcial"),
                            ("pending", "Pendente"),
                            ("overdue", "Atrasado"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "commission",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Comissão (35%)",
                    ),
                ),
                (
                    "profit",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="Lucro"
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("cash", "Dinheiro"),
                            ("pix", "PIX"),
                            ("card", "Cartão"),
                            ("debit", "Débito"),
                        ],
                        default="cash",
                        max_length=20,
                        verbose_name="Forma de pagamento",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Venda",
                "verbose_name_plural": "Vendas",
                "ordering": ["-created_at"],
            },
        ),
    ]
