# Generated by Django 4.2.30 on 2026-05-13 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="status",
            field=models.CharField(
                choices=[
                    ("paid", "Pago"),
                    ("partial", "Parcial"),
                    ("pending", "Pendente"),
                    ("overdue", "Atrasado"),
                    ("canceled", "Cancelado"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
