# Generated by Django 4.2.30 on 2026-05-14 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="ai_imported",
            field=models.BooleanField(default=False, verbose_name="Importado por IA"),
        ),
        migrations.AddField(
            model_name="product",
            name="original_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Nome original OCR"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="supplier_code",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Código fornecedor"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("lingerie", "Lingerie"),
                    ("cueca", "Cueca"),
                    ("meia", "Meia"),
                    ("camiseta", "Camiseta"),
                    ("moletom", "Moletom"),
                    ("legging", "Legging"),
                    ("segunda_pele", "Segunda pele"),
                ],
                default="lingerie",
                max_length=50,
                verbose_name="Categoria",
            ),
        ),
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "total_products",
                    models.IntegerField(default=0, verbose_name="Total produtos"),
                ),
                (
                    "total_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Valor total",
                    ),
                ),
                (
                    "raw_ocr_text",
                    models.TextField(
                        blank=True, null=True, verbose_name="Texto OCR bruto"
                    ),
                ),
                (
                    "original_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="imports/",
                        verbose_name="Imagem original",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lote de importação",
                "verbose_name_plural": "Lotes de importação",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="import_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="products.importbatch",
            ),
        ),
    ]
